// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class AuthPermission
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int ContentTypeId { get; set; }

    public string Codename { get; set; }

    public virtual ICollection<AuthGroupPermission> AuthGroupPermissions { get; set; } = new List<AuthGroupPermission>();

    public virtual ICollection<AuthUserUserPermission> AuthUserUserPermissions { get; set; } = new List<AuthUserUserPermission>();

    public virtual DjangoContentType ContentType { get; set; }
}