// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class ComponentDevice
{
    public int Id { get; set; }

    public int? ComponentId { get; set; }

    public int? MasterId { get; set; }

    public DateOnly? Installdate { get; set; }
}