// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Designation
{
    public int DsId { get; set; }

    public string DsName { get; set; }

    public int? DepartmentId { get; set; }
}