// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class DeviceAssign
{
    public int Id { get; set; }

    public int? Deviceid { get; set; }

    public DateTime? Installationdatetime { get; set; }

    public int? AddressId { get; set; }

    public int? Approverpersonid { get; set; }

    public int? EntityId { get; set; }

    public string Remarks { get; set; }

    public int? OrgId { get; set; }
}