// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class DeviceAttribute
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Unit { get; set; }

    public decimal? MinValue { get; set; }

    public decimal? MaxValue { get; set; }

    public decimal? StandardValue { get; set; }

    public string Remarks { get; set; }
}