// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Deviceinstallation
{
    public int Id { get; set; }

    public int DeviceId { get; set; }

    public int AddressId { get; set; }

    public int ApproverPersonId { get; set; }

    public string Status { get; set; }

    public DateTime? InstallDate { get; set; }

    public string Image { get; set; }

    public int EntityId { get; set; }

    public string Remarks { get; set; }

    public decimal? MinValue { get; set; }

    public decimal? MaxValue { get; set; }

    public decimal? MaxSever { get; set; }
}