// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Devicetype
{
    public int Id { get; set; }

    public decimal? SendingFerq { get; set; }

    public string PositionAccuracy { get; set; }

    public decimal? PrtectionRating { get; set; }

    public string OpreatingVoltage { get; set; }

    public string HotStart { get; set; }

    public string WarmStart { get; set; }

    public string ColdStart { get; set; }

    public string HumidityLevel { get; set; }

    public string OpreatingTemp { get; set; }

    public string Sensitivity { get; set; }

    public string ActiveModePeak { get; set; }

    public string ActiveModeAvg { get; set; }

    public string BatteryBackup { get; set; }

    public string SleepMode { get; set; }

    public string UsbPort { get; set; }

    public string GpsReciver { get; set; }

    public decimal? GpsAccuracy { get; set; }

    public string Protocol { get; set; }

    public string Antenna { get; set; }

    public string Bluetooth { get; set; }

    public decimal? DeviceLife { get; set; }

    public string Model { get; set; }

    public string BatteryMah { get; set; }

    public int? Channels { get; set; }

    public string Band2g { get; set; }

    public string RfPower { get; set; }

    public string Datacoding { get; set; }

    public string CommProtocol { get; set; }

    public string DigitalInput { get; set; }

    public string DigitalOutput { get; set; }

    public string AnalogInput { get; set; }

    public string Memory { get; set; }

    public string Firmwareupdate { get; set; }

    public string Sms { get; set; }

    public string Certificates { get; set; }

    public string Sos { get; set; }
}