// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class DeviceDetail
{
    public int Id { get; set; }

    public int DTypeId { get; set; }

    public int AttributeId { get; set; }
}