// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class DjangoAdminLog
{
    public int Id { get; set; }

    public DateTime ActionTime { get; set; }

    public string ObjectId { get; set; }

    public string ObjectRepr { get; set; }

    public ushort ActionFlag { get; set; }

    public string ChangeMessage { get; set; }

    public int? ContentTypeId { get; set; }

    public int UserId { get; set; }

    public virtual DjangoContentType ContentType { get; set; }

    public virtual AuthUser User { get; set; }
}