// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class DjangoMigration
{
    public long Id { get; set; }

    public string App { get; set; }

    public string Name { get; set; }

    public DateTime Applied { get; set; }
}