// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Employeedevice
{
    public int Id { get; set; }

    public int? PersonId { get; set; }

    public int? DeviceId { get; set; }

    public DateTime? Assigntime { get; set; }

    public ulong? Status { get; set; }
}