// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Entity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string LongName { get; set; }

    public string TradeName { get; set; }

    public int? EntityTypeId { get; set; }

    public int? EntityRoleId { get; set; }

    public string Remarks { get; set; }

    public virtual Entityrole EntityRole { get; set; }

    public virtual Entitytype EntityType { get; set; }
}