// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Entityaddress
{
    public int Id { get; set; }

    public int? Entityid { get; set; }

    public int? Addressid { get; set; }

    public int? Addresstype { get; set; }

    public virtual Address Address { get; set; }
}