// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Entitytype
{
    public int TypeId { get; set; }

    public string EntityTypeName { get; set; }

    public virtual ICollection<Entity> Entities { get; set; } = new List<Entity>();
}