// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Entityaddressview
{
    public int EntityAddressId { get; set; }

    public int? EntityId { get; set; }

    public int? AddressId { get; set; }

    public string Addressline1 { get; set; }

    public string Addressline2 { get; set; }

    public string Pincode { get; set; }

    public int? CityId { get; set; }

    public string CityName { get; set; }

    public int? StateId { get; set; }

    public string StateName { get; set; }

    public int? CountryId { get; set; }

    public string CountryName { get; set; }

    public int? WardId { get; set; }

    public string WardName { get; set; }

    public int? RegionId { get; set; }

    public string RegionName { get; set; }

    public int? ZoneId { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public string Remarks { get; set; }

    public int? AddressType { get; set; }

    public string AddressTypeName { get; set; }
}