// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Ferrerodatafabricationconfig
{
    public int Id { get; set; }

    public string Imie { get; set; }

    public int? MinTemp { get; set; }

    public int? MaxTemp { get; set; }
}