// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Imagedetail
{
    public int Id { get; set; }

    public string Imageurl { get; set; }

    public int? ImageTypeId { get; set; }

    public string UniqueId { get; set; }
}