// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Iotdatafabricated
{
    public long Id { get; set; }

    public string Temperature { get; set; }

    public string Lattitude { get; set; }

    public string Longitude { get; set; }

    public string Imie { get; set; }

    public string Ischarging { get; set; }

    public string Batteryvoltage { get; set; }

    public string Humidity { get; set; }

    public string Signalstrength { get; set; }

    public DateTime? Lastreportingtime { get; set; }

    public string Deviceid { get; set; }

    public string Receiveddatapacket { get; set; }

    public string Devicetype { get; set; }

    public string Header { get; set; }

    public string Datatype { get; set; }

    public string Datapacketsrnum { get; set; }

    public string Datasource { get; set; }

    public string Time { get; set; }

    public string Date { get; set; }

    public string Temperaturealert { get; set; }
}