// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Location
{
    public int Id { get; set; }

    public string Locationname { get; set; }

    public int? Addressid { get; set; }
}