// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class MasterDeviceType
{
    public int Id { get; set; }

    public string DeviceName { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public string Remarks { get; set; }
}