// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Organisationaddress
{
    public int Id { get; set; }

    public int? OrgId { get; set; }

    public int? AddressId { get; set; }

    public int? Addresstype { get; set; }
}