// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Person
{
    public int Id { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Mobilenumber { get; set; }

    public string Email { get; set; }

    public string Imageurl { get; set; }

    public int? Contacttype { get; set; }

    public string Alternatenumber { get; set; }

    public string Remarks { get; set; }
}