// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Rdlocation
{
    public int Id { get; set; }

    public int? RdId { get; set; }

    public int? Locationid { get; set; }
}