// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Regionaldistributor
{
    public int Id { get; set; }

    public string Rdname { get; set; }

    public string Rdcode { get; set; }
}