// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Region
{
    public int RegionId { get; set; }

    public string Regionname { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();
}