// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Userlogintype
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public int? RoleId { get; set; }
}