// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class VwTotaldevice
{
    public int? Entityid { get; set; }

    public string Name { get; set; }

    public int? AddressId { get; set; }

    public string Addressline1 { get; set; }

    public string Addressline2 { get; set; }

    public string Longitude { get; set; }

    public string Latitude { get; set; }

    public int? WardId { get; set; }

    public string WardName { get; set; }

    public int? ZoneId { get; set; }

    public string Zonename { get; set; }

    public int? RegionId { get; set; }

    public string RegionName { get; set; }

    public int? StateId { get; set; }

    public string StateName { get; set; }

    public string Person { get; set; }

    public string MobileNumber { get; set; }

    public int? DeviceId { get; set; }

    public string Imie { get; set; }

    public string AssetId { get; set; }

    public decimal? MinValue { get; set; }

    public decimal? MaxValue { get; set; }

    public decimal? MaxSever { get; set; }

    public int? Devicetypeid { get; set; }

    public DateTime? InstallationDate { get; set; }

    public string DeviceType { get; set; }

    public int? OrgId { get; set; }

    public string OrgName { get; set; }

    public string OrgCode { get; set; }
}