// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Ward
{
    public int WardId { get; set; }

    public string Wardname { get; set; }

    public int? Stateid { get; set; }

    public virtual State State { get; set; }
}