// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AjeeviIoT.Models;

public partial class Zone
{
    public int ZoneId { get; set; }

    public string Zonename { get; set; }
}